### ISSUE TITLE
occasional  random crashes with "concurrent write to websocket connection" error.

### ISSUE THREAD

**Issue by kusayuzayushko** [0mlml/chesshook-intermediary#1]
it mostly works stable, sometimes multiple games with no errors at all. Not sure what exactly triggers that.  Any idea?

```
recv: go nodes 3
engine: info depth 1 seldepth 2 time 3 nodes 2 score cp 127 tbhits 0 pv f3h2 h5e2
engine: info depth 2 seldepth 3 time 7 nodes 3 score cp 40 nps 1000 tbhits 0 pv f3h2 h5e2 d1e2
engine: bestmove f3h2 ponder h5e2
recv: unsub
ws closed: 127.0.0.1:49074
http: panic serving 127.0.0.1:49074: concurrent write to websocket connection
goroutine 10 [running]:
net/http.(*conn).serve.func1()
        /usr/lib/go/src/net/http/server.go:1868 +0xb9
panic({0x74ee60?, 0x85b8c0?})
        /usr/lib/go/src/runtime/panic.go:920 +0x270
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0000bf890, 0x1, {0xc000288097?, 0xc000288090?, 0x7?})
        /home/crypt/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:617 +0x4b8
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc0000fe160, 0x7c3f90?, {0xc000288090, 0x7, 0x8})
        /home/crypt/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:770 +0x127
main.(*User).send(0xc000012150, {0x7c3f90?, 0x85b0f8?})
        /home/crypt/chess/chesshook-intermediary/main.go:129 +0x45
main.wsHandler({0x85f4c0?, 0xc000220000?}, 0xc0000bfb18?)
        /home/crypt/chess/chesshook-intermediary/main.go:236 +0x7c5
net/http.HandlerFunc.ServeHTTP(0x445a00?, {0x85f4c0?, 0xc000220000?}, 0x6fd67a?)
        /usr/lib/go/src/net/http/server.go:2136 +0x29
net/http.(*ServeMux).ServeHTTP(0xae2100?, {0x85f4c0, 0xc000220000}, 0xc00021a000)
        /usr/lib/go/src/net/http/server.go:2514 +0x142
net/http.serverHandler.ServeHTTP({0xc000091980?}, {0x85f4c0?, 0xc000220000?}, 0x6?)
        /usr/lib/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc000216000, {0x85fc10, 0xc000091890})
        /usr/lib/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 1
        /usr/lib/go/src/net/http/server.go:3086 +0x5cb
```

**Comment by 0mlml** [comment]
I never experienced this issue, but this should fix it.
